spring:
  application:
    name: service-discovery-producer
  cloud:
    services:
      registrationMethod: direct
 # for apps.internal(Conatiner to container) use registrationMethod: direct
 # default routing registrationMethod: route